monkey = _{
	"Monkey" ~ id ~ ":" ~
    "Starting items:" ~ items ~
    "Operation: new = old" ~ operation ~
    "Test: divisible by" ~ number ~
    "If true: throw to monkey" ~ id ~
    "If false: throw to monkey" ~ id ~
    EOI
}
id = @{ number }
items = { item ~ ("," ~ item)* }
item = @{ number }
operation = _{ op_add | op_mul | op_square }
op_add = { "+" ~ number }
op_mul = { "*" ~ number }
op_square = { "*" ~ "old" }
number = @{ '0'..'9'+ }
WHITESPACE = _{ "\n" | " " }